/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class net_blueberrymc_native_util_NativeAccessor */

#ifndef _Included_net_blueberrymc_native_util_NativeAccessor
#define _Included_net_blueberrymc_native_util_NativeAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_blueberrymc_native_util_NativeAccessor
 * Method:    appendToBootstrapClassLoaderSearch
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_blueberrymc_native_1util_NativeAccessor_appendToBootstrapClassLoaderSearch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_blueberrymc_native_util_NativeAccessor
 * Method:    appendToSystemClassLoaderSearch
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_blueberrymc_native_1util_NativeAccessor_appendToSystemClassLoaderSearch
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
