name: CMake

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
      - working-directory: ${{runner.workspace}}/build
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          ls ./x64
          ls ./Release
      - if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: libnativeutil.dylib
          path: '${{runner.workspace}}/build/libnativeutil.dylib'
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: libnativeutil.so
          path: '${{runner.workspace}}/build/libnativeutil.so'
      - if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: nativeutil.dll
          path: '${{runner.workspace}}/build/x64/nativeutil.dll'
